services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://store-na-phx-2.gofile.io/download/web/2f096c26-82ee-41ef-8ed2-749d7a5b0811/Windows_XP.iso"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
      DISK_SIZE: "70G"
      DISK_TYPE: "ide"
      BOOT_MODE: "windows_legacy"
      VGA: "std"
      NETWORK: "N"
      TPM: "N"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./zinc:/oem
      - ./winc:/data    
    restart: always
    stop_grace_period: 2m
