services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/windows-10-build-9913/10.0.9913.0.fbl_awesome1501.141217-1931_amd64fre_client-professional_retail_en-us-J_CPRA_X64FRE_EN-US_DV5.iso"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
      DISK_SIZE: "70G"
      NETWORK: "N"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage     
      - ./winc:/data    
    restart: always
    stop_grace_period: 2m
