services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/4074_twiwmtb/lh_usa_4074_x86fre_pro-dvd.iso"
      PLATFORM: "x86"
      RAM_SIZE: "2GB"
      CPU_CORES: "1"
      DISK_TYPE: "ide"
      BOOT_MODE: "windows_legacy"
      VGA: "cirrus"
      TPM: "N"
      ARGUMENTS: "-boot d -cpu host -usbdevice tablet -rtc base=2004-05-01,clock=vm -drive file=/lh_usa_4074_x86fre_pro-dvd.iso,media=cdrom,interface=ide -accel tcg"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./winc:/data
    restart: always
    stop_grace_period: 2m

