services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/Windows10Build10031Debombed/Windows%2010%20Build%2010031%20%28EN-US%2C%20Debombed%2C%20UEFI%20Only%29.iso"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
      DISK_SIZE: "70G"
      MANUAL: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage     
      - ./winc:/data    
    restart: always
    stop_grace_period: 2m
