services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/Windows-Server_22364/22364.1000.210416-1749.rs_fun_SERVERSTANDARD_OEMRET_x64fre_en-us.iso"
      RAM_SIZE: "8GB"
      CPU_CORES: "1"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./winc:/data
    restart: always
    stop_grace_period: 2m

