services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/win-11-english-x64/Win11_English_x64.iso"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
      DISK_SIZE: "70G"
      BOOT_MODE: "windows_secure"
      TPM: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage     
      - ./winc:/data    
    restart: always
    stop_grace_period: 2m
