services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/Windows10build10102ENx64/10.0.10102.0.winmain_prs.150417-2325_amd64fre_client-professional-core_retail_en-us-J_CCSA_X64FRE_EN-US_DV5.iso"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
      DISK_SIZE: "70G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage     
      - ./winc:/data    
    restart: always
    stop_grace_period: 2m
